### ISSUE TITLE
大佬，你的QQ加不上呀

### ISSUE THREAD

**Issue by Achelics** [toolgood/ToolGood.TextFilter#1]
QQ加了，没有人回复，那还有其它渠道可以获取敏感词么

**Comment by toolgood** [comment]
目前笔记本坏了，正在维修，下个星期吧，备份的不是最新的。增加渠道我正在考虑中



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年11月18日(星期四) 上午9:07
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [toolgood/ToolGood.TextFilter] 大佬，你的QQ加不上呀 (Issue #1)





 
QQ加了，没有人回复，那还有其它渠道可以获取敏感词么
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
